### ISSUE TITLE
Passing raster layer rather than path causes set_envir error

### ISSUE THREAD

**Issue by jsta** [apear9/rdwplus#1]
I get an error when passing a raster object to set_envir:

```
library(rdwplus)
initGRASS("/usr/lib/grass78", home = tempdir())
dem <- raster(in_path)
rdwplus::set_envir(dem)

> Error in doGRASS(cmd, flags = flags, ..., parameters = parameters, echoCmd = echoCmd,  : 
  Parameter <georef> has multiple values
```

However, if I pass a raster path instead the code works:
```
rdwplus::set_envir(in_path)
```

Perhaps `set_envir` need to pull the file path when passed a raster object? Maybe the following line would be a fix?

```
else {
        r_layer <- layer
        layer <- slot(slot(layer, "file"), "name")
    }

```

**Comment by apear9** [comment]
Sorry I've been away for so long. 

Thanks for bringing this to my attention. I will investigate. 

Cheers,

Alan

**Comment by apear9** [comment]
I resolved the problem. The solution implemented is similar to the one you suggested. Thanks!
